// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeAdZbjcoA46ViBIlpH0_qLQthXezC1zc',
    appId: '1:228893967276:web:f4f5c2cbf253ef9ff93009',
    messagingSenderId: '228893967276',
    projectId: 'summit-7132c',
    authDomain: 'summit-7132c.firebaseapp.com',
    storageBucket: 'summit-7132c.firebasestorage.app',
    measurementId: 'G-9B7ETZ136T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA78oplULYhPvUXXFO-s72X6aXQH6P4sEc',
    appId: '1:228893967276:android:cc5f14386f572bb9f93009',
    messagingSenderId: '228893967276',
    projectId: 'summit-7132c',
    storageBucket: 'summit-7132c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9ND5aeeddY0U9GAxFNeXWffkA4Lc9wEw',
    appId: '1:228893967276:ios:13e0ace60ddb08c3f93009',
    messagingSenderId: '228893967276',
    projectId: 'summit-7132c',
    storageBucket: 'summit-7132c.firebasestorage.app',
    iosBundleId: 'com.example.testAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9ND5aeeddY0U9GAxFNeXWffkA4Lc9wEw',
    appId: '1:228893967276:ios:13e0ace60ddb08c3f93009',
    messagingSenderId: '228893967276',
    projectId: 'summit-7132c',
    storageBucket: 'summit-7132c.firebasestorage.app',
    iosBundleId: 'com.example.testAppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeAdZbjcoA46ViBIlpH0_qLQthXezC1zc',
    appId: '1:228893967276:web:7b5b28569b65c1dff93009',
    messagingSenderId: '228893967276',
    projectId: 'summit-7132c',
    authDomain: 'summit-7132c.firebaseapp.com',
    storageBucket: 'summit-7132c.firebasestorage.app',
    measurementId: 'G-NKJB7JF09B',
  );
}
